---
- hosts: all
  tasks:
    - name: Build hosts file (backups will be made
      lineinfile: dest=/etc/hosts regexp='{{ hostvars[item].ansible_hostname }}$' line='{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ hostvars[item].ansible_hostname }}' state=present backup=yes
      when: hostvars[item].ansible_default_ipv4.address is defined
      with_items: groups['all']

  roles:
    - { role: ansible-http-proxy, proxy_server: 'http://192.168.112.14:3128', tags: ['http-proxy'] }
    - { role: ansible-tuna, tags: ['tuna'] }
    - { role: ansible-opencv, tags: ['opencv'] }

- hosts: [mesos_masters]
  sudo: True
  tags: [ mesos-masters ]
  pre_tasks:
    - name: Install HAProxy
      apt: pkg=haproxy state=present
    - name: Sets haproxy to enabled
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
  roles:
    - { role: 'ansible-java8', tags: ['runtimes', 'java'] }
    - { role: 'ansible-zookeeper', zookeeper_hosts: "{{ groups.mesos_masters }}", tags: ['zookeeper'] }
    - { role: 'ansible-mesos',
        mesos_version: "0.23.0",
        mesos_quorum: "2", 
        zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}", 
        mesos_install_mode: 'master', mesos_cluster_name: 'mlh_mesos', tags: ['mesos', 'platforms'] }

- hosts: [mesos_slaves]
  sudo: True
  tags: [ mesos-slaves ]
  pre_tasks:
    - name: Remove require tty
      lineinfile: regexp="tty" dest=/etc/sudoers/os_defaults state=absent
      tags: ['system']
  roles:
    - { role: 'ansible-docker', tags: ['docker'] }
    - { role: 'ansible-java8', tags: ['java'] }
    - { role: 'ansible-mesos', mesos_containerizers: "docker,mesos",
        mesos_version: "0.23.0",
        zookeeper_hostnames: "{{ groups.mesos_masters | join(':' + zookeeper_client_port + ',')  }}:{{ zookeeper_client_port  }}",
        mesos_quorum: "2",
        mesos_install_mode: "slave", tags:  ['mesos'] }
    - { role: 'ansible-mesos-spark',
        spark_download_url: "http://mesos-master-1/spark-1.6.0-SNAPSHOT-bin-spark-master-tachyon-0.8.0.tgz",
        spark_download_md5sum: "9a40e4d7e901d4753d87db4b937f056c",
        spark_directory_name: "spark-1.6.0-SNAPSHOT-bin-spark-master-tachyon-0.8.0",
        tags: ['ansible-mesos-spark'] }
